jQuery(document).ready(function () {
    jQuery('#cf_submission_camp_default_css').attr("readonly", "readonly");
    jQuery('#cf_submission_camp_default_css').css("background-color", "#cccccc");
    jQuery('#cf_single_product_contribution_table_default_css').attr('readonly', 'readonly');
    jQuery('#cf_single_product_contribution_table_default_css').css('background-color', '#cccccc');
    jQuery('#cf_shop_page_contribution_table_default_css').attr("readonly", "readonly");
    jQuery('#cf_shop_page_contribution_table_default_css').css('background-color', '#ccc');
    jQuery('.out-of-stock').css('clear', 'both');
});
jQuery(function () {
    jQuery('#single_product_prog_bar_type').change(function () {
        if (jQuery('#load_inbuilt_design').val() == '1') {
            if (jQuery('#single_product_prog_bar_type').val() == '1') {
                jQuery('#cf_single_product_contribution_table_default_css').val(" #cf_update_total_funderers {display:none;} \n\ #cf_target_price_labelers {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} \n\ #cf_update_total_funderers {display:none;} \n\  #cf_target_price_labelers {display:none;}#cf_min_price_label { display:block;\n\ } \n\ #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ }\n\#cf_total_price_in_percentage_with_bar{\n\ width: 100%;\n\ height:12px;\n\ background-color: #ffffff;\n\ border-radius:10px;\n\ border:1px solid #000000;\n\ } \n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } ");
            } else {
                jQuery('#cf_single_product_contribution_table_default_css').val(" #cf_update_total_funderers {display:none;} \n\ #cf_target_price_labelers {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} \n\ #cf_update_total_funderers {display:none;} \n\  #cf_target_price_labelers {display:none;}#cf_min_price_label { display:block;\n\ } \n\ #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ } \n\ .pledgetracker{height: 10px;\n\  border-radius: 5px;\n\ position: relative; \n\ background: #f3efe6; \n\overflow: hidden; \n\} \n\ .rightsidepledge {float:right; \n\} \n\ .pledgetracker span {display: block; \n\ height: 100%;\n\} \n\ .currentpledgegoal {background-color: #c66799; \n\ -webkit-animation: currentpledgebar 2s ease-in-out; \n\ -webkit-animation-fill-mode:both; \n\ -moz-animation: currentpledgebar 2s ease-in-out; \n\ -moz-animation-fill-mode:both; \n\} \n\ @-webkit-keyframes currentpledgebar{ 0% { width: 0; } \n\ 100% { width: 100%; } \n\ } c  @-moz-keyframes currentpledgebar {0% { width: 0; } \n\  100% { width: 100%; } \n\ } \n\ ");
            }
        } else if (jQuery('#load_inbuilt_design').val() == '2') {
            if (jQuery('#single_product_prog_bar_type').val() == '1') {
                jQuery('#cf_single_product_contribution_table_default_css').val(" #cf_update_total_funderers {display:none;} \n\ #cf_target_price_labelers {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\#cf_total_price_raise span {font-size:30px; \n\ }\n\#cf_total_price_in_percent{ \n\ }\n\#cf_total_price_in_percent_with_bar{width: 100% !important;\n\ height:12px !important; \n\ background-color: #ffffff !important; \n\ border-radius:10px !important; \n\ border:1px solid #000000 !important; \n\ clear:both; \n\ } \n\ #cf_percent_bar{ height:10px !important; \n\ border-radius:10px !important; \n\ background-color: green !important; \n\ } \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\ font-size:30px !important;\n\ margin-bottom:0px;\n\}");
            } else {
                jQuery('#cf_single_product_contribution_table_default_css').val(" #cf_update_total_funderers {display:none;} \n\ #cf_target_price_labelers {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\#cf_total_price_raise span {font-size:30px; \n\ }\n\#cf_total_price_in_percent{ \n\ }\n\ .pledgetracker{height: 10px;\n\  border-radius: 5px;\n\ position: relative; \n\ background: #f3efe6; \n\overflow: hidden; \n\} \n\ .rightsidepledge {float:right; \n\} \n\ .pledgetracker span {display: block; \n\ height: 100%;\n\} \n\ .currentpledgegoal {background-color: #c66799; \n\ -webkit-animation: currentpledgebar 2s ease-in-out; \n\ -webkit-animation-fill-mode:both; \n\ -moz-animation: currentpledgebar 2s ease-in-out; \n\ -moz-animation-fill-mode:both; \n\} \n\ @-webkit-keyframes currentpledgebar{ 0% { width: 0; } \n\ 100% { width: 100%; } \n\ } c  @-moz-keyframes currentpledgebar {0% { width: 0; } \n\  100% { width: 100%; } \n\ } \n\ \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\ font-size:30px !important;\n\ margin-bottom:0px;\n\}");
            }
        } else {
            if (jQuery('#single_product_prog_bar_type').val() == '1') {
                jQuery('#cf_single_product_contribution_table_default_css').val(".pledgetracker{display:none;}\n\#cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ .totalfundercounts {font-size:40px;} \n\ #cf_total_pricer_raiser {font-size:40px;} \n\ #cf_total_price_raiser {margin-bottom:0px;} \n\  #newdateremains {font-size:30px;} \n\ #cf_total_price_in_percentage_with_bar{\n\ width: 100%;\n\ height:12px;\n\ background-color: #ffffff;\n\ border-radius:10px;\n\ border:1px solid #000000;\n\ } \n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\#cf_total_price_in_percenter_with_bar{width: 100%;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ } \n\ #cf_percenter_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
            } else {
                jQuery('#cf_single_product_contribution_table_default_css').val(".pledgetracker{display:none;}\n\ #cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ .totalfundercounts {font-size:40px;} \n\ #cf_total_pricer_raiser {font-size:40px;} \n\ #cf_total_price_raiser {margin-bottom:0px;} \n\ #cf_total_price_in_percent_with_bar {display:none;} #newdateremains {font-size:30px;} \n\ #cf_total_price_in_percentage_with_bar{\n\ width: 100%;\n\ height:12px;\n\ background-color: #ffffff;\n\ border-radius:10px;\n\ border:1px solid #000000;\n\ } \n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ }  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\#cf_total_price_in_percenter_with_bar{width: 100%;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ } \n\ #cf_percenter_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
            }
        }
    });
    jQuery('#load_inbuilt_design').change(function () {
        switch (jQuery(this).val())
        {
            case "1":
            {
                if (jQuery('#single_product_prog_bar_type').val() == '1') {
                    jQuery('#cf_single_product_contribution_table_default_css').val(" #cf_update_total_funderers {display:none;} \n\ #cf_target_price_labelers {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} \n\ #cf_update_total_funderers {display:none;} \n\  #cf_target_price_labelers {display:none;}#cf_min_price_label { display:block;\n\ } \n\ #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ }\n\#cf_total_price_in_percentage_with_bar{\n\ width: 100%;\n\ height:12px;\n\ background-color: #ffffff;\n\ border-radius:10px;\n\ border:1px solid #000000;\n\ } \n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } ");
                    break;
                } else {
                    jQuery('#cf_single_product_contribution_table_default_css').val(" #cf_update_total_funderers {display:none;} \n\ #cf_target_price_labelers {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} \n\ #cf_update_total_funderers {display:none;} \n\  #cf_target_price_labelers {display:none;}#cf_min_price_label { display:block;\n\ } \n\ #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ } \n\ .pledgetracker{height: 10px;\n\  border-radius: 5px;\n\ position: relative; \n\ background: #f3efe6; \n\overflow: hidden; \n\} \n\ .rightsidepledge {float:right; \n\} \n\ .pledgetracker span {display: block; \n\ height: 100%;\n\} \n\ .currentpledgegoal {background-color: #c66799; \n\ -webkit-animation: currentpledgebar 2s ease-in-out; \n\ -webkit-animation-fill-mode:both; \n\ -moz-animation: currentpledgebar 2s ease-in-out; \n\ -moz-animation-fill-mode:both; \n\} \n\ @-webkit-keyframes currentpledgebar{ 0% { width: 0; } \n\ 100% { width: 100%; } \n\ } c  @-moz-keyframes currentpledgebar {0% { width: 0; } \n\  100% { width: 100%; } \n\ } \n\ ");
                    break;
                }
            }
            case "2":
            {
                if (jQuery('#single_product_prog_bar_type').val() == '1') {
                    jQuery('#cf_single_product_contribution_table_default_css').val(" #cf_update_total_funderers {display:none;} \n\ #cf_target_price_labelers {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\#cf_total_price_raise span {font-size:30px; \n\ }\n\#cf_total_price_in_percent{ \n\ }\n\#cf_total_price_in_percent_with_bar{width: 100% !important;\n\ height:12px !important; \n\ background-color: #ffffff !important; \n\ border-radius:10px !important; \n\ border:1px solid #000000 !important; \n\ clear:both; \n\ } \n\ #cf_percent_bar{ height:10px !important; \n\ border-radius:10px !important; \n\ background-color: green !important; \n\ } \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\ font-size:30px !important;\n\ margin-bottom:0px;\n\}");
                    break;
                } else {
                    jQuery('#cf_single_product_contribution_table_default_css').val(" #cf_update_total_funderers {display:none;} \n\ #cf_target_price_labelers {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\#cf_total_price_raise span {font-size:30px; \n\ }\n\#cf_total_price_in_percent{ \n\ }\n\ .pledgetracker{height: 10px;\n\  border-radius: 5px;\n\ position: relative; \n\ background: #f3efe6; \n\overflow: hidden; \n\} \n\ .rightsidepledge {float:right; \n\} \n\ .pledgetracker span {display: block; \n\ height: 100%;\n\} \n\ .currentpledgegoal {background-color: #c66799; \n\ -webkit-animation: currentpledgebar 2s ease-in-out; \n\ -webkit-animation-fill-mode:both; \n\ -moz-animation: currentpledgebar 2s ease-in-out; \n\ -moz-animation-fill-mode:both; \n\} \n\ @-webkit-keyframes currentpledgebar{ 0% { width: 0; } \n\ 100% { width: 100%; } \n\ } c  @-moz-keyframes currentpledgebar {0% { width: 0; } \n\  100% { width: 100%; } \n\ } \n\ \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\ font-size:30px !important;\n\ margin-bottom:0px;\n\}");
                    break;
                }
            }
            case "3":
            {
                if (jQuery('#single_product_prog_bar_type').val() == '1') {
                    jQuery('#cf_single_product_contribution_table_default_css').val(".pledgetracker{display:none;}\n\ #cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ .totalfundercounts {font-size:40px;} \n\ #cf_total_pricer_raiser {font-size:40px;} \n\ #cf_total_price_raiser {margin-bottom:0px;} \n\  #newdateremains {font-size:30px;} \n\ #cf_total_price_in_percentage_with_bar{\n\ width: 100%;\n\ height:12px;\n\ background-color: #ffffff;\n\ border-radius:10px;\n\ border:1px solid #000000;\n\ } \n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\#cf_total_price_in_percenter_with_bar{width: 100%;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ } \n\ #cf_percenter_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
                    break;
                } else {
                    jQuery('#cf_single_product_contribution_table_default_css').val(".pledgetracker{display:none;}\n\ #cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ .totalfundercounts {font-size:40px;} \n\ #cf_total_pricer_raiser {font-size:40px;} \n\ #cf_total_price_raiser {margin-bottom:0px;} \n\ #cf_total_price_in_percent_with_bar {display:none;} #newdateremains {font-size:30px;} \n\ #cf_total_price_in_percentage_with_bar{\n\ width: 100%;\n\ height:12px;\n\ background-color: #ffffff;\n\ border-radius:10px;\n\ border:1px solid #000000;\n\ } \n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\#cf_total_price_in_percenter_with_bar{display:none}; \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
                    break;
                }
            }
        }
    });
});
jQuery(function () {

    jQuery('#shop_page_prog_bar_type').change(function () {
        selectedvalue = jQuery('#load_inbuilt_shop_design').val();
        if (selectedvalue == '1') {
            if (jQuery('#shop_page_prog_bar_type').val() == '1') {
                jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_total_price_in_percenter_with_bar{display:none;}\n\#cf_min_price_label { display:block;\n\ }\n\.pledgetracker{display:none;}\n\ #cf_get_total_funders {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ }\n\#cf_total_price_in_percent_with_bar{display:none;}\n\#cf_total_price_in_percentage_with_bar{\n\ width: 100%;\n\ height:12px;\n\ background-color: #ffffff;\n\ border-radius:10px;\n\ border:1px solid #000000;\n\ } \n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } ");
            } else {
                jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_total_price_in_percenter_with_bar{display:none;}\n\#cf_min_price_label { display:block;\n\ } #cf_get_total_funders {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_total_price_in_percentage_with_bar {display:none;}\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ }\n\#cf_total_price_in_percent_with_bar{display:none;}\n\ .pledgetracker{height: 10px;\n\  border-radius: 5px;\n\ position: relative; \n\ background: #f3efe6; \n\overflow: hidden; \n\} \n\ .rightsidepledge {float:right; \n\} \n\ .pledgetracker span {display: block; \n\ height: 100%;\n\} \n\ .currentpledgegoal {background-color: #c66799; \n\ -webkit-animation: currentpledgebar 2s ease-in-out; \n\ -webkit-animation-fill-mode:both; \n\ -moz-animation: currentpledgebar 2s ease-in-out; \n\ -moz-animation-fill-mode:both; \n\} \n\ @-webkit-keyframes currentpledgebar{ 0% { width: 0; } \n\ 100% { width: 100%; } \n\ } c  @-moz-keyframes currentpledgebar {0% { width: 0; } \n\  100% { width: 100%; } \n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } ");
            }
        } else if (selectedvalue == '2') {
            if (jQuery('#shop_page_prog_bar_type').val() == '1') {
                jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_total_price_in_percenter_with_bar{display:none;}\n\#cf_min_price_label { display:none;\n\ } \n\.pledgetracker{display:none;}\n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\#cf_total_price_in_percent{ \n\ }\n\#cf_total_price_in_percent_with_bar{width: 100%;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ } \n\ #cf_percent_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\margin-bottom:0px;\n\}");
            } else {
                jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_total_price_in_percenter_with_bar{display:none;}\n\ #cf_min_price_label { display:none;\n\ } \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\ \n\#cf_total_price_in_percent_with_bar{display:none;}\n\#cf_total_price_in_percent{ \n\ }\n\.pledgetracker{height: 10px;\n\  border-radius: 5px;\n\ position: relative; \n\ background: #f3efe6; \n\overflow: hidden; \n\} \n\ .rightsidepledge {float:right; \n\} \n\ .pledgetracker span {display: block; \n\ height: 100%;\n\} \n\ .currentpledgegoal {background-color: #c66799; \n\ -webkit-animation: currentpledgebar 2s ease-in-out; \n\ -webkit-animation-fill-mode:both; \n\ -moz-animation: currentpledgebar 2s ease-in-out; \n\ -moz-animation-fill-mode:both; \n\} \n\ @-webkit-keyframes currentpledgebar{ 0% { width: 0; } \n\ 100% { width: 100%; } \n\ } c  @-moz-keyframes currentpledgebar {0% { width: 0; } \n\  100% { width: 100%; } \n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\ margin-bottom:0px;\n\}");
            }
        } else {
            if (jQuery('#shop_page_prog_bar_type').val() == '1') {
                jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_min_price_label { display:none;\n\ } \n\.pledgetracker{display:none;}\n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\#cf_total_price_in_percenter_with_bar{width: 100%;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ }#cf_percenter_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ \n\.pledgetracker span {display: none;}\n\ #cf_total_price_in_percent_with_bar{display:none; \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
            } else {
                jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_total_price_in_percenter_with_bar{display:none;}\n\#cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\.pledgetracker{height: 10px;\n\  border-radius: 5px;\n\ position: relative; \n\ background: #f3efe6; \n\overflow: hidden; \n\} \n\ .rightsidepledge {float:right; \n\} \n\#cf_total_price_in_percent_with_bar{display:none;}\n\ .pledgetracker span {display: block; \n\ height: 100%;\n\} \n\ .currentpledgegoal {background-color: #c66799; \n\ -webkit-animation: currentpledgebar 2s ease-in-out; \n\ -webkit-animation-fill-mode:both; \n\ -moz-animation: currentpledgebar 2s ease-in-out; \n\ -moz-animation-fill-mode:both; \n\} \n\ @-webkit-keyframes currentpledgebar{ 0% { width: 0; } \n\ 100% { width: 100%; } \n\ } c  @-moz-keyframes currentpledgebar {0% { width: 0; } \n\  100% { width: 100%; } \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
            }
        }
    })
    jQuery('#load_inbuilt_shop_design').change(function () {
        switch (jQuery(this).val())
        {
            case "1":
            {
                if (jQuery('#shop_page_prog_bar_type').val() == '1') {
                    jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_total_price_in_percenter_with_bar{display:none;}\n\#cf_min_price_label { display:block;\n\ }\n\.pledgetracker{display:none;}\n\ #cf_get_total_funders {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ }\n\#cf_total_price_in_percent_with_bar{display:none;}\n\#cf_total_price_in_percentage_with_bar{\n\ width: 100%;\n\ height:12px;\n\ background-color: #ffffff;\n\ border-radius:10px;\n\ border:1px solid #000000;\n\ } \n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } ");
                    break;
                } else {
                    jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_total_price_in_percenter_with_bar{display:none;}\n\#cf_min_price_label { display:block;\n\ } #cf_get_total_funders {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_total_price_in_percentage_with_bar {display:none;}\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ }\n\#cf_total_price_in_percent_with_bar{display:none;}\n\ .pledgetracker{height: 10px;\n\  border-radius: 5px;\n\ position: relative; \n\ background: #f3efe6; \n\overflow: hidden; \n\} \n\ .rightsidepledge {float:right; \n\} \n\ .pledgetracker span {display: block; \n\ height: 100%;\n\} \n\ .currentpledgegoal {background-color: #c66799; \n\ -webkit-animation: currentpledgebar 2s ease-in-out; \n\ -webkit-animation-fill-mode:both; \n\ -moz-animation: currentpledgebar 2s ease-in-out; \n\ -moz-animation-fill-mode:both; \n\} \n\ @-webkit-keyframes currentpledgebar{ 0% { width: 0; } \n\ 100% { width: 100%; } \n\ } c  @-moz-keyframes currentpledgebar {0% { width: 0; } \n\  100% { width: 100%; } \n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } ");
                    break;
                }
            }
            case "2":
            {
                if (jQuery('#shop_page_prog_bar_type').val() == '1') {
                    jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_total_price_in_percenter_with_bar{display:none;}\n\#cf_min_price_label { display:none;\n\ } \n\.pledgetracker{display:none;}\n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\#cf_total_price_in_percent{ \n\ }\n\#cf_total_price_in_percent_with_bar{width: 100%;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ } \n\ #cf_percent_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\ margin-bottom:0px;\n\}");
                    break;
                } else {
                    jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_total_price_in_percenter_with_bar{display:none;}\n\ #cf_min_price_label { display:none;\n\ } \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\ \n\#cf_total_price_in_percent_with_bar{display:none;}\n\#cf_total_price_in_percent{ \n\ }\n\.pledgetracker{height: 10px;\n\  border-radius: 5px;\n\ position: relative; \n\ background: #f3efe6; \n\overflow: hidden; \n\} \n\ .rightsidepledge {float:right; \n\} \n\ .pledgetracker span {display: block; \n\ height: 100%;\n\} \n\ .currentpledgegoal {background-color: #c66799; \n\ -webkit-animation: currentpledgebar 2s ease-in-out; \n\ -webkit-animation-fill-mode:both; \n\ -moz-animation: currentpledgebar 2s ease-in-out; \n\ -moz-animation-fill-mode:both; \n\} \n\ @-webkit-keyframes currentpledgebar{ 0% { width: 0; } \n\ 100% { width: 100%; } \n\ } c  @-moz-keyframes currentpledgebar {0% { width: 0; } \n\  100% { width: 100%; } \n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\margin-bottom:0px;\n\}");
                    break;
                }
            }
            case "3":
            {
                if (jQuery('#shop_page_prog_bar_type').val() == '1') {
                    jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_min_price_label { display:none;\n\ } \n\.pledgetracker{display:none;}\n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\#cf_total_price_in_percenter_with_bar{width: 100%;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ }#cf_percenter_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ \n\.pledgetracker span {display: none;}\n\ #cf_total_price_in_percent_with_bar{display:none; \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
                    break;
                } else {
                    jQuery('#cf_shop_page_contribution_table_default_css').val("#cf_total_price_in_percenter_with_bar{display:none;}\n\#cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\.pledgetracker{height: 10px;\n\  border-radius: 5px;\n\ position: relative; \n\ background: #f3efe6; \n\overflow: hidden; \n\} \n\ .rightsidepledge {float:right; \n\} \n\#cf_total_price_in_percent_with_bar{display:none;}\n\ .pledgetracker span {display: block; \n\ height: 100%;\n\} \n\ .currentpledgegoal {background-color: #c66799; \n\ -webkit-animation: currentpledgebar 2s ease-in-out; \n\ -webkit-animation-fill-mode:both; \n\ -moz-animation: currentpledgebar 2s ease-in-out; \n\ -moz-animation-fill-mode:both; \n\} \n\ @-webkit-keyframes currentpledgebar{ 0% { width: 0; } \n\ 100% { width: 100%; } \n\ } c  @-moz-keyframes currentpledgebar {0% { width: 0; } \n\  100% { width: 100%; } \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
                    break;
                }
            }
        }
    });
});
jQuery(function () {
    jQuery('#shortcode_page_prog_bar_type').change(function () {

        if (jQuery('#load_inbuilt_shop_design_shortcode').val() == '1')
        {
            if (jQuery('#shortcode_page_prog_bar_type').val() == '1') {
                jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_total_price_in_percent_with_bar{display:none;} \n\ #cf_total_price_in_percenter_with_bar{display:none;} \n\#cf_min_price_label { display:block;\n\ } #cf_get_total_funders {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ }\n\#cf_total_price_in_percentage_with_bar{\n\ width: 100%;\n\ height:12px;\n\ background-color: #ffffff;\n\ border-radius:10px;\n\ border:1px solid #000000;\n\ } \n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } ");
            } else {
                jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_total_price_in_percentage_with_bar {display:none;}\n\#cf_total_price_in_percenter_with_bar{display:none;} \n\#cf_total_price_in_percent_with_bar{display:none;} \n\#cf_min_price_label { display:block;\n\ } #cf_get_total_funders {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ }\n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } ");
            }
        }

        else if (jQuery('#load_inbuilt_shop_design_shortcode').val() == '2') {
            if (jQuery('#shortcode_page_prog_bar_type').val() == '1') {
                jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_min_price_label { display:none;\n\ } \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\#cf_total_price_raise span {font-size:17px; \n\ }\n\#cf_total_price_in_percent_with_bar{width: 100%;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ } \n\ #cf_percent_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\ font-size:16px !important;\n\ margin-bottom:0px;\n\}");
            } else {
                jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_min_price_label { display:none;\n\ } \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\#cf_total_price_in_percenter_with_bar{display:none;}\n\#cf_total_price_raise span {font-size:17px; \n\ }\n\#cf_total_price_in_percent_with_bar{display:none;} \n\ #cf_percent_bar{ display:none;\n\ } \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\ font-size:16px !important;\n\ margin-bottom:0px;\n\}");
            }
        }

        else
        {
            if (jQuery('#shortcode_page_prog_bar_type').val() == '1') {
                jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_total_price_in_percent_with_bar{display:none;} \n\#cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\#cf_total_price_in_percenter_with_bar{width: 100%;\n\ margin-top:10px;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ } \n\ #cf_percenter_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
            } else {
                jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_total_price_in_percent_with_bar{display:none;} \n\#cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\#cf_total_price_in_percenter_with_bar{display:none;} \n\ #cf_percenter_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
            }
        }
    });
    jQuery('#load_inbuilt_shop_design_shortcode').change(function () {
        switch (jQuery(this).val())
        {
            case "1":
            {
                if (jQuery('#shortcode_page_prog_bar_type').val() == '1') {
                    jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_min_price_label { display:block;\n\ }\n\ #cf_total_price_in_percenter_with_bar{display:none;} \n\#cf_total_price_in_percent_with_bar{display:none;} \n\#cf_get_total_funders {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ }\n\#cf_total_price_in_percentage_with_bar{\n\ width: 100%;\n\ height:12px;\n\ background-color: #ffffff;\n\ border-radius:10px;\n\ border:1px solid #000000;\n\ } \n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } ");
                    break;
                } else {
                    jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_total_price_in_percentage_with_bar {display:none;}\n\#cf_total_price_in_percenter_with_bar{display:none;} \n\#cf_total_price_in_percent_with_bar{display:none;} \n\#cf_min_price_label { display:block;\n\ } #cf_get_total_funders {display:none;} \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} #cf_days_remaining {display:none;} #cf_total_price_raise {display:none;} \n\ #cf_target_price_labels {display:none;} \n\ #cf_price_new_date_remain {display:none;} \n\ #cf_update_total_funders {display:none;} \n\ #cf_total_raised_percentage {display:none;} #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_min_price_label{ \n\ }\n\#cf_max_price_label{ \n\ }\n\#cf_target_price_label{ \n\ }\n\#cf_total_price_raised{ \n\ }\n\#cf_total_price_in_percentage{ \n\ }\n\ #cf_percentage_bar{ height:10px;\n\ border-radius:10px;\n\ background-color: green;\n\ } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } ");
                    break;
                }

            }
            case "2":
            {
                if (jQuery('#shortcode_page_prog_bar_type').val() == '1') {
                    jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_min_price_label { display:none;\n\ } \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\#cf_total_price_raise span {font-size:17px; \n\ }\n\#cf_total_price_in_percent_with_bar{width: 100%;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ } \n\ #cf_percent_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\ font-size:16px !important;\n\ margin-bottom:0px;\n\}");
                    break;
                } else {
                    jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_min_price_label { display:none;\n\ } \n\ #cf_total_raised_in_percentage { display:none; } \n\ #cf_total_price_raiser {display:none;} \n\ #cf_days_remainings {display:none;} \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ float:left; \n\ }\n\#cf_total_price_in_percenter_with_bar{display:none;}\n\#cf_total_price_raise span {font-size:17px; \n\ }\n\\n\#cf_total_price_in_percent_with_bar{display:none;} \n\ #cf_percent_bar{ display:none;\n\ } \n\ #cf_price_new_date_remain small { font-style:italic;  } \n\ #cf_price_new_date_remain { margin-bottom:0px;\n\ float:left; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {font-style:italic;\n\ font-size:20px;\n\ } \n\ #cf_update_total_funders {margin-bottom:0px; float:right; } \n\ #cf_total_raised_percentage {float:right;\n\ font-size:16px !important;\n\ margin-bottom:0px;\n\}");
                    break;
                }
            }
            case "3":
            {
                if (jQuery('#shortcode_page_prog_bar_type').val() == '1') {
                    jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_total_price_in_percent_with_bar{display:none;} \n\#cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\#cf_total_price_in_percenter_with_bar{width: 100%;\n\ margin-top:10px;\n\ height:12px; \n\ background-color: #ffffff; \n\ border-radius:10px; \n\ border:1px solid #000000; \n\ clear:both; \n\ } \n\ #cf_percenter_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
                    break;
                } else {
                    jQuery('#cf_shop_page_contribution_table_default_css_shortcode').val("#cf_total_price_in_percent{display:none;}\n\#cf_total_price_in_percenter_with_bar{display:none;} \n\#cf_total_price_in_percent_with_bar{display:none;} \n\#cf_min_price_label { display:none;\n\ } \n\ #cf_max_price_label { display:none; }\n\ #cf_target_price_label { display:none; }\n\  #cf_total_price_raised {display:none;} \n\ #cf_total_price_in_percentage_with_bar {display:none;} \n\ #cf_total_price_in_percentage {display:none;}  #single_product_contribution_table{ \n\ }\n\#cf_serial_number_label{ \n\ }\n\#cf_contributor_label{ \n\ }\n\#cf_contributor_email_label{ \n\ }\n\#cf_contribution_label{ \n\ }\n\#cf_date_label{ \n\ }\n\#serial_id{ \n\ }\n\#cf_billing_first_name{ \n\ } \n\ #cf_billing_email{ \n\ } \n\ #cf_order_total{ \n\ }\n\#cf_target_price_labels{ margin-bottom:0px; \n\ }\n\#cf_total_price_raise{ display:none; \n\ }\n\#cf_total_price_raise span {display:none; \n\ }\n\#cf_total_price_in_percenter{ \n\ }\n\ #cf_percenter_bar{ height:10px; \n\ border-radius:10px; \n\ background-color: green; \n\ } \n\ #cf_price_new_date_remain small { display:none;} \n\ #cf_price_new_date_remain { display:none; } \n\ #singleproductinputfieldcrowdfunding{color:green; \n\ } \n\ #cf_target_price_labels {display:none; } \n\ #cf_update_total_funders {display:none } \n\ #cf_total_raised_percentage {display:none;} \n\ #cf_days_remaining { display:none;\n\ } \n\ #cf_total_price_raiser { \n\ } \n\ #cf_total_raised_in_percentage { \n\ } \n\ #cf_get_total_funders {display:none;}");
                    break;
                }
            }
        }
    });
});
